services:
  - type: web
    name: star-wars-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: star-wars-db
          property: connectionString
      - key: NODE_ENV
        value: production

databases:
  - name: star-wars-db
    plan: free
